advancedtelematic/ota-tuf

build.sbt
Needs mono installed already for checking for files.
=> Don't even launch the check for dotnet deps

cli/src/main/scala/com/advancedtelematic/tuf/cli/Cli.scala, cli/src/main/scala/com/advancedtelematic/tuf/cli/CliHelp.scala, cli/src/main/scala/com/advancedtelematic/tuf/cli/repo/TufRepo.scala, cli/src/test/scala/com/advancedtelematic/tuf/cli/CliSpec.scala, cli/src/test/scala/com/advancedtelematic/tuf/cli/TufRepoSpec.scala, libtuf/src/main/scala/com/advancedtelematic/libtuf/data/ClientDataType.scala, libtuf/src/main/scala/com/advancedtelematic/libtuf/http/SHttpjServiceClient.scala, libtuf/src/main/scala/com/advancedtelematic/libtuf/reposerver/UserReposerverClient.scala, reposerver/src/main/scala/com/advancedtelematic/tuf/reposerver/http/Errors.scala, reposerver/src/main/scala/com/advancedtelematic/tuf/reposerver/http/RepoResource.scala, reposerver/src/main/scala/com/advancedtelematic/tuf/reposerver/http/RoleChecksumHeader.scala, reposerver/src/test/scala/com/advancedtelematic/tuf/reposerver/http/RepoResourceSpec.scala, reposerver/src/test/scala/com/advancedtelematic/tuf/reposerver/http/UserReposerverClientSpec.scala, reposerver/src/test/scala/com/advancedtelematic/tuf/reposerver/util/ResourceSpec.scala
This reverts commit af1ef499e982ae21f501547c4194937ae24833af.
=> Revert "Revert "Merge pull request #140 from advancedtelematic/feat/PRO-4546/custom_header""

build.sbt, deploy/ci_setup.sh, reposerver/src/main/scala/com/advancedtelematic/tuf/reposerver/http/OfflineSignedRoleStorage.scala, reposerver/src/main/scala/com/advancedtelematic/tuf/reposerver/http/RepoResource.scala, reposerver/src/main/scala/com/advancedtelematic/tuf/reposerver/http/TufReposerverRoutes.scala, reposerver/src/test/scala/com/advancedtelematic/tuf/reposerver/http/OfflineSignedRoleStorageSpec.scala, reposerver/src/test/scala/com/advancedtelematic/tuf/reposerver/http/RepoResourceNamespaceExtractionSpec.scala, reposerver/src/test/scala/com/advancedtelematic/tuf/reposerver/http/RepoResourceSpec.scala, reposerver/src/test/scala/com/advancedtelematic/tuf/reposerver/http/S3StorageResourceIntegrationSpec.scala
Also returning checksum on initial target upload.
(mkdir param change is for MacOS.)
=> Fire TufTargetAdded for new targets

cli/src/main/scala/com/advancedtelematic/tuf/cli/repo/RepoManagement.scala, keyserver/src/test/scala/com/advancedtelematic/tuf/keyserver/client/KeyserverHttpClientSpec.scala, keyserver/src/test/scala/com/advancedtelematic/tuf/keyserver/daemon/KeyGeneratorLeaderSpec.scala, keyserver/src/test/scala/com/advancedtelematic/tuf/keyserver/daemon/KeyGeneratorWorkerIntegrationSpec.scala, keyserver/src/test/scala/com/advancedtelematic/tuf/keyserver/daemon/KeyGeneratorWorkerSpec.scala, keyserver/src/test/scala/com/advancedtelematic/tuf/keyserver/http/RoleSigningSpec.scala, keyserver/src/test/scala/com/advancedtelematic/tuf/keyserver/http/RootRoleGenerationSpec.scala, keyserver/src/test/scala/com/advancedtelematic/tuf/keyserver/http/RootRoleResourceSpec.scala, keyserver/src/test/scala/com/advancedtelematic/tuf/keyserver/vault/VaultClientIntegrationSpec.scala, keyserver/src/test/scala/com/advancedtelematic/tuf/keyserver/vault/VaultTokenRenewerSpec.scala, libtuf/build.sbt, libtuf/src/main/scala/com/advancedtelematic/libtuf/data/TufDataType.scala
=> Extend tests to Ed25519

cli/src/test/scala/com/advancedtelematic/tuf/cli/CliKeyStorageSpec.scala, cli/src/test/scala/com/advancedtelematic/tuf/cli/CliSpec.scala, cli/src/test/scala/com/advancedtelematic/tuf/cli/TufRepoSpec.scala, cli/src/test/scala/com/advancedtelematic/tuf/cli/repo/RepoManagementSpec.scala, keyserver/src/test/scala/com/advancedtelematic/tuf/keyserver/client/KeyserverHttpClientSpec.scala, keyserver/src/test/scala/com/advancedtelematic/tuf/keyserver/daemon/KeyGeneratorLeaderSpec.scala, keyserver/src/test/scala/com/advancedtelematic/tuf/keyserver/daemon/KeyGeneratorWorkerIntegrationSpec.scala, keyserver/src/test/scala/com/advancedtelematic/tuf/keyserver/daemon/KeyGeneratorWorkerSpec.scala, keyserver/src/test/scala/com/advancedtelematic/tuf/keyserver/http/RootRoleResourceSpec.scala, keyserver/src/test/scala/com/advancedtelematic/tuf/keyserver/http/SignedRootRolesSpec.scala, keyserver/src/test/scala/com/advancedtelematic/tuf/keyserver/roles/RoleSigningSpec.scala, keyserver/src/test/scala/com/advancedtelematic/tuf/keyserver/vault/VaultClientIntegrationSpec.scala, keyserver/src/test/scala/com/advancedtelematic/tuf/util/ResourceSpec.scala, libtuf/src/main/scala/com/advancedtelematic/libtuf/data/TufDataType.scala
=> Use trait for key type tests

cli/src/test/scala/com/advancedtelematic/tuf/cli/TufRepoSpec.scala, libtuf-server/src/main/scala/com/advancedtelematic/libtuf_server/data/Marshalling.scala, reposerver/src/main/scala/com/advancedtelematic/tuf/reposerver/Boot.scala, reposerver/src/main/scala/com/advancedtelematic/tuf/reposerver/http/RepoResource.scala, reposerver/src/test/scala/com/advancedtelematic/tuf/reposerver/client/ReposerverHttpClientSpec.scala, reposerver/src/test/scala/com/advancedtelematic/tuf/reposerver/http/OfflineSignedRoleStorageSpec.scala, reposerver/src/test/scala/com/advancedtelematic/tuf/reposerver/http/RepoResourceNamespaceExtractionSpec.scala, reposerver/src/test/scala/com/advancedtelematic/tuf/reposerver/http/RepoResourceSpec.scala, reposerver/src/test/scala/com/advancedtelematic/tuf/reposerver/http/S3StorageResourceIntegrationSpec.scala, reposerver/src/test/scala/com/advancedtelematic/tuf/reposerver/http/UserReposerverClientSpec.scala, reposerver/src/test/scala/com/advancedtelematic/tuf/reposerver/util/NamespaceSpecOps.scala, reposerver/src/test/scala/com/advancedtelematic/tuf/reposerver/util/ResourceSpec.scala, reposerver/src/test/scala/com/advancedtelematic/tuf/reposerver/util/TufReposerverSpec.scala
Optional parameter for the repo creation endpoint to allow to specify the type of the root key.
=> KeyType parameter for repo creation endpoint

cli/src/main/scala/com/advancedtelematic/tuf/cli/Cli.scala
Fix regression introduced with 101d161
=> Exit with status code 3 on exception

keyserver/src/test/scala/com/advancedtelematic/tuf/keyserver/daemon/KeyGeneratorLeaderSpec.scala
Fixes
http://teamcity.staging.internal.atsgarage.com:8111/viewLog.html?buildId=12281&tab=buildResultsDiv&buildTypeId=Staging_Test_OtaTufTest
=> Timeout too short

cli/src/main/scala/com/advancedtelematic/tuf/cli/Cli.scala, cli/src/main/scala/com/advancedtelematic/tuf/cli/repo/TufRepo.scala, cli/src/test/scala/com/advancedtelematic/tuf/cli/TufRepoSpec.scala, reposerver/src/main/scala/com/advancedtelematic/tuf/reposerver/db/Repository.scala, reposerver/src/main/scala/com/advancedtelematic/tuf/reposerver/db/TreehubStorageMethodFix.scala, reposerver/src/main/scala/com/advancedtelematic/tuf/reposerver/http/RepoResource.scala, reposerver/src/main/scala/com/advancedtelematic/tuf/reposerver/http/SignedRoleGeneration.scala, reposerver/src/main/scala/com/advancedtelematic/tuf/reposerver/target_store/LocalTargetStoreEngine.scala, reposerver/src/main/scala/com/advancedtelematic/tuf/reposerver/target_store/S3TargetStoreEngine.scala, reposerver/src/main/scala/com/advancedtelematic/tuf/reposerver/target_store/TargetStore.scala, reposerver/src/main/scala/com/advancedtelematic/tuf/reposerver/target_store/TargetStoreEngine.scala, reposerver/src/main/scala/db/migration/R__TreehubStorageMethodFix.scala, reposerver/src/test/scala/com/advancedtelematic/tuf/reposerver/http/RepoResourceSpec.scala
Fix bug when unmanaged targets were added as managed
=> Allow package deletion from online targets

build.sbt, keyserver/src/main/scala/com/advancedtelematic/tuf/keyserver/Boot.scala, keyserver/src/main/scala/com/advancedtelematic/tuf/keyserver/http/RootRoleResource.scala, keyserver/src/main/scala/com/advancedtelematic/tuf/keyserver/http/TufKeyserverRoutes.scala
Bump libats
Depends on https://github.com/advancedtelematic/libats/pull/54
=> expose /metrics with prometheus format

reposerver/src/test/scala/com/advancedtelematic/tuf/reposerver/util/ResourceSpec.scala
Test was failing because signature was computed dynamically, therefore different for each request.
=> Store signed roots in test keyserver, not just roots

.github/dco.yml, cli/src/main/scala/com/advancedtelematic/tuf/cli/Cli.scala, cli/src/main/scala/com/advancedtelematic/tuf/cli/client/UserReposerverHttpClient.scala, cli/src/main/scala/com/advancedtelematic/tuf/cli/repo/RepoManagement.scala, libtuf/src/main/scala/com/advancedtelematic/libtuf/reposerver/UserTufServerClient.scala
For the DCO config see https://github.com/probot/dco/blob/master/README.md.
=> garage-sign talks to the director through the API gateway

build.sbt, keyserver/src/main/scala/com/advancedtelematic/tuf/keyserver/Boot.scala, keyserver/src/test/scala/com/advancedtelematic/tuf/keyserver/client/KeyserverHttpClientSpec.scala, libtuf-server/src/main/scala/com/advancedtelematic/libtuf_server/keyserver/KeyserverClient.scala, reposerver/src/main/scala/com/advancedtelematic/tuf/reposerver/Boot.scala, reposerver/src/main/scala/com/advancedtelematic/tuf/reposerver/http/RepoResource.scala
Very hacky code to trace akka requests on server and client
=> add request tracing

README.md, cli/README.adoc, cli/src/main/scala/com/advancedtelematic/tuf/cli/Cli.scala, cli/src/main/scala/com/advancedtelematic/tuf/cli/CliConfigOptionOps.scala, cli/src/main/scala/com/advancedtelematic/tuf/cli/CommandHandler.scala, cli/src/main/scala/com/advancedtelematic/tuf/cli/Commands.scala, cli/src/main/scala/com/advancedtelematic/tuf/cli/Delegations.scala, cli/src/main/scala/com/advancedtelematic/tuf/cli/WriteOutput.scala, cli/src/main/scala/com/advancedtelematic/tuf/cli/repo/TufRepo.scala, cli/src/test/scala/com/advancedtelematic/tuf/cli/CommandHandlerSpec.scala, cli/src/test/scala/com/advancedtelematic/tuf/cli/DelegationsSpec.scala, cli/src/test/scala/com/advancedtelematic/tuf/cli/TufRepoSpec.scala
Add documentation for delegations use case to cli/README
=> Add `delegations add-target` command

libtuf-server/src/main/scala/com/advancedtelematic/libtuf_server/reposerver/ReposerverClient.scala, reposerver/src/test/scala/com/advancedtelematic/tuf/reposerver/util/ResourceSpec.scala
Signed-off-by: Simão Mata <simao.mata@here.com>
=> add tracing support to reposerver client trace http

build.sbt, cli/build.sbt, cli/src/test/scala/com/advancedtelematic/tuf/cli/TufRepoMoveOfflineSpec.scala, libtuf-server/src/main/scala/com/advancedtelematic/libtuf_server/data/Messages.scala
Signed-off-by: Jerry Trieu <jerry.trieu@here.com>
=> Bump to libats-0.2.0, akka-2.5.20

cli/README.adoc
See https://github.com/advancedtelematic/ota-tuf/blob/master/cli/src/main/scala/com/advancedtelematic/tuf/cli/Cli.scala#L147
=> Typo in README

cli/README.adoc, keyserver/src/main/scala/com/advancedtelematic/tuf/keyserver/db/Repository.scala, keyserver/src/main/scala/com/advancedtelematic/tuf/keyserver/roles/KeyGenerationRequests.scala, keyserver/src/test/scala/com/advancedtelematic/tuf/keyserver/http/RootRoleResourceSpec.scala
=> POST offline signed role deletes old keys

reposerver/src/main/scala/com/advancedtelematic/tuf/reposerver/http/SignedRoleGeneration.scala, reposerver/src/test/scala/com/advancedtelematic/tuf/reposerver/http/RepoResourceDelegationsSpec.scala
=> Keep delegations when adding TargetItem

cli/README.adoc, cli/src/main/scala/com/advancedtelematic/tuf/cli/Delegations.scala, cli/src/main/scala/com/advancedtelematic/tuf/cli/Errors.scala, cli/src/test/scala/com/advancedtelematic/tuf/cli/DelegationsSpec.scala
Signed-off-by: Simão Mata <simao.mata@here.com>
=> Throw explicit error when adding a target to signed delegations file

cli/README.adoc
Signed-off-by: Simão Mata <simao.mata@here.com>
=> add reference to add-target/--uri in cli/README

cli/src/main/scala/com/advancedtelematic/tuf/cli/Cli.scala, cli/src/main/scala/com/advancedtelematic/tuf/cli/CliHelp.scala, cli/src/main/scala/com/advancedtelematic/tuf/cli/CliReads.scala, cli/src/main/scala/com/advancedtelematic/tuf/cli/CommandHandler.scala, cli/src/main/scala/com/advancedtelematic/tuf/cli/Errors.scala, cli/src/main/scala/com/advancedtelematic/tuf/cli/repo/TufRepo.scala, cli/src/test/scala/com/advancedtelematic/tuf/cli/CommandHandlerExpirationDateSpec.scala, cli/src/test/scala/com/advancedtelematic/tuf/cli/CommandHandlerSpec.scala, cli/src/test/scala/com/advancedtelematic/tuf/cli/TufRepoMoveOfflineSpec.scala, cli/src/test/scala/com/advancedtelematic/tuf/cli/TufRepoSpec.scala
=> Options for setting the expiration date when signing

cli/README.adoc, cli/src/main/scala/com/advancedtelematic/tuf/cli/CommandHandler.scala
Also added an explanation about giving dates on the command line to the
README.
=> Convert to UTC, not days internally

keyserver/src/main/scala/com/advancedtelematic/tuf/keyserver/daemon/KeyGenerationDaemon.scala, reposerver/src/main/scala/com/advancedtelematic/tuf/reposerver/Boot.scala
Add /metrics endpoint to keyserver daemon
=> Add http response metrics to reposerver

reposerver/src/main/resources/application.conf
See https://github.com/advancedtelematic/director/pull/191
Signed-off-by: Simão Mata <simao.mata@here.com>
=> increase akka connection pool

cli/src/main/scala/com/advancedtelematic/tuf/cli/Cli.scala, cli/src/main/scala/com/advancedtelematic/tuf/cli/repo/RepoManagement.scala, cli/src/main/scala/com/advancedtelematic/tuf/cli/repo/TufRepo.scala, cli/src/test/scala/com/advancedtelematic/tuf/cli/TufRepoSpec.scala
=> Only unpack root.json from credentials.zip into reposerver repos
